for250:
    build: .
    container_name: for250
#    envfile:
#        - for250.env
    command: gunicorn --name for250 -b 0.0.0.0:1690 -w 2 wsgi:app
    ports:
        - "1690:1690"
    external_links:
        - mysqlfor250:mysql
    links:
        - redis

redis:
    image: redis
    volumes:
        - .:/redisdata
    command: redis-server --appendonly yes --port 6380
    ports:
        - "6380:6380"
